### ISSUE TITLE
Packagist Registration

### ISSUE THREAD

**Issue by beam2web** [nimius/news-blog#10]
Hello nimius,

can you please also register news-blog on https://packagist.org/ ?

It is the main Composer repository to install public PHP packages with Composer.

Best regards

**Comment by pduersteler** [comment]
Hi

We're most likely abandon the package, therefore I'm closing this issue. If it won't get abandoned, we may consider it.

**Comment by copitz** [comment]
Hi Pascal,

ok - FYI, I just put it on packagist via my fork as we desperately need it from packagist. Please drop me a note if you decide not to abandon the package so that I can then in turn abandon our fork :1234: 

Thank you, cheers,
Christian

**Comment by pduersteler** [comment]
Not sure why you need it on packagist, you can register another repository inside composer.json and get it from any source you want. I'll notify you here if anything changes.
