### ISSUE TITLE
Author Name not showing in Typo3 version 8

### ISSUE THREAD

**Issue by DesignsToGrow** [nimius/news-blog#11]
When i try to add the header with {news.authorRecord} i get nothing. If i try it with {newsItem.authorRecord} i get the following instead: NIMIUS\NewsBlog\Domain\Model\Author:3
Is this a compatibility issue with v8? Also the extended field does not recognize pagebreaks. It would be nice to have the rte editor here.

**Comment by pduersteler** [comment]
When `{newsItem.authorRecord}` gets you `NIMIUS\NewsBlog\Domain\Model\Author:3`, it's working; You're getting a string representation of the author object. Now you need to call the appropriate methods on it to get the data you desire. Have a look into the `Author` model for more information.
